============================= test session starts ==============================
platform linux -- Python 3.8.18, pytest-8.3.3, pluggy-1.5.0 -- /opt/hostedtoolcache/Python/3.8.18/x64/bin/python
cachedir: .pytest_cache
rootdir: /home/runner/work/arrow/arrow
configfile: tox.ini
plugins: cov-5.0.0
collecting ... collected 0 items


---------- coverage: platform linux, python 3.8.18-final-0 -----------
Name                 Stmts   Miss  Cover   Missing
--------------------------------------------------
arrow/__init__.py        7      7     0%   1-21
arrow/_version.py        1      1     0%   1
arrow/api.py            30     30     0%   7-126
arrow/arrow.py         558    558     0%   7-1873
arrow/constants.py      12     12     0%   3-37
arrow/factory.py        89     89     0%   8-344
arrow/formatter.py     101    101     0%   3-141
arrow/locales.py      1176   1176     0%   3-6645
arrow/parser.py        314    314     0%   3-936
arrow/util.py           45     45     0%   3-117
--------------------------------------------------
TOTAL                 2333   2333     0%
Coverage XML written to file coverage.xml

FAIL Required test coverage of 99% not reached. Total coverage: 0.00%
============================ no tests ran in 0.69s =============================
============================= test session starts ==============================
platform linux -- Python 3.8.18, pytest-8.3.3, pluggy-1.5.0 -- /opt/hostedtoolcache/Python/3.8.18/x64/bin/python
cachedir: .pytest_cache
rootdir: /home/runner/work/arrow/arrow
configfile: tox.ini
plugins: cov-5.0.0
collecting ... collected 0 items / 1 error

==================================== ERRORS ====================================
___________ ERROR collecting generated_tests/python/test_factory.py ____________
ImportError while importing test module '/home/runner/work/arrow/arrow/generated_tests/python/test_factory.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
generated_tests/python/test_factory.py:8: in <module>
    from arrow import ArrowFactory, Arrow
arrow/__init__.py:2: in <module>
    from .api import get, now, utcnow
arrow/api.py:12: in <module>
    from arrow.arrow import TZ_EXPR, Arrow
arrow/arrow.py:33: in <module>
    from dateutil import tz as dateutil_tz
E   ModuleNotFoundError: No module named 'dateutil'

---------- coverage: platform linux, python 3.8.18-final-0 -----------
Name                 Stmts   Miss Branch BrPart  Cover   Missing
----------------------------------------------------------------
arrow/__init__.py        7      5      0      0    29%   3-21
arrow/_version.py        1      0      0      0   100%
arrow/api.py            30     25      0      0    17%   13-126
arrow/arrow.py         558    546    247      0     1%   34-1873
arrow/constants.py      12     12      0      0     0%   3-37
arrow/factory.py        89     89     50      0     0%   8-344
arrow/formatter.py     101    101     72      0     0%   3-141
arrow/locales.py      1176   1176    180      0     0%   3-6645
arrow/parser.py        314    314    144      0     0%   3-936
arrow/util.py           45     45     22      0     0%   3-117
----------------------------------------------------------------
TOTAL                 2333   2313    715      0     1%
Coverage XML written to file coverage.xml

FAIL Required test coverage of 99% not reached. Total coverage: 0.66%
=========================== short test summary info ============================
ERROR generated_tests/python/test_factory.py
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
=============================== 1 error in 1.10s ===============================
